### ISSUE TITLE
Licence file?

### ISSUE THREAD

**Issue by davelab6** [ohbendy/IAST-shortcuts#1]
Please add a license to the repo, as without one, it is impossible to make copies legally, including downloading :)

**Comment by ohbendy** [comment]
Oh! Where can I find an example one? I don't know any of this stuff :-)

**Comment by davelab6** [comment]
GitHub made www.ChooseALicense.com for you, as well as www.opensource.guide
:)

**Comment by ohbendy** [comment]
Added unlicence.txt. Thanks Dave.
